# Generated by Django 6.0.7 on 2026-08-17 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCOUNT_CREATED', 'Innovator account created'), ('ACCOUNT_UPDATED', 'Account updated'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('OTP_RESENT', 'Activation code resent'), ('ATTENDANCE_CORRECTED', 'Attendance corrected'), ('INCOMPLETE_SESSION_CLOSED', 'Incomplete session closed'), ('ROLE_CHANGED', 'User role changed')], max_length=40)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='auditlog_au_action_c6fc70_idx'), models.Index(fields=['target_model', 'target_id'], name='auditlog_au_target__13695c_idx')],
            },
        ),
    ]
