# Generated by Django 6.0.7 on 2026-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Innovator account added'), ('ACCOUNT_UPDATED', 'Account updated'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('TEMPORARY_CREDENTIALS_REISSUED', 'Temporary login credentials reissued'), ('ATTENDANCE_CORRECTED', 'Attendance corrected'), ('INCOMPLETE_SESSION_CLOSED', 'Incomplete session closed'), ('ROLE_CHANGED', 'User role changed')], max_length=40),
        ),
    ]
