# Generated by Django 6.0.7 on 2026-08-18 20:08

from django.db import migrations, models


def preserve_first_login_state(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(activation_completed=False).update(must_change_password=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountactivationotp',
            name='accounts_ac_user_id_394982_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_first_login_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='activation_completed',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Password change required'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='AccountActivationOTP',
        ),
    ]
