# Generated by Django 6.0.7 on 2026-08-17 11:01

import django.db.models.deletion
import django.utils.timezone
import innovators.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[innovators.models.validate_kenyan_phone])),
                ('course', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('innovation_project_name', models.CharField(max_length=200)),
                ('project_category', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('AGRICULTURE', 'Agriculture'), ('CLIMATE', 'Climate and environment'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=30)),
                ('date_joined', models.DateField(default=django.utils.timezone.localdate)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/')),
                ('biography', models.TextField(blank=True)),
                ('project_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='innovator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
