# Generated by Django 6.0.7 on 2026-08-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovatorprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='innovatorprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='innovatorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='innovatorprofile',
            name='project_category',
        ),
        migrations.RemoveField(
            model_name='innovatorprofile',
            name='year_of_study',
        ),
    ]
