# Generated by Django 6.0.7 on 2026-08-21 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_existing_profile_projects(apps, schema_editor):
    InnovatorProfile = apps.get_model("innovators", "InnovatorProfile")
    InnovatorProject = apps.get_model("innovators", "InnovatorProject")
    projects = []
    for profile in InnovatorProfile.objects.all().iterator():
        name = (profile.innovation_project_name or "").strip()
        if not name:
            continue
        projects.append(
            InnovatorProject(
                profile_id=profile.pk,
                name=name,
                details=(profile.project_description or "").strip()
                or "No project details were provided in the original profile.",
                area_of_focus="Not specified",
            )
        )
    InnovatorProject.objects.bulk_create(projects)


class Migration(migrations.Migration):

    dependencies = [
        ('innovators', '0003_remove_innovatorprofile_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovatorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('details', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('area_of_focus', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='innovators.innovatorprofile')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['profile', 'created_at'], name='innovators__profile_eb5a67_idx'), models.Index(fields=['area_of_focus'], name='innovators__area_of_40a37e_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_project_name_per_innovator', violation_error_message='You already have a project with this name.')],
            },
        ),
        migrations.RunPython(copy_existing_profile_projects, migrations.RunPython.noop),
    ]
