# Generated by Django 6.0.7 on 2026-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovators', '0004_innovatorproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovatorprofile',
            name='innovation_project_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
