# Generated by Django 6.0.7 on 2026-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='planned_activity',
            field=models.TextField(blank=True),
        ),
    ]
