# Generated by Django 6.0.7 on 2026-08-21 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancesession_planned_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ADMITTED', 'Admitted')], default='BOOKED', max_length=20)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admitted_hub_bookings', to=settings.AUTH_USER_MODEL)),
                ('innovator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-arrival_time', '-created_at'],
                'indexes': [models.Index(fields=['visit_date', 'status', 'arrival_time'], name='attendance__visit_d_644fb0_idx'), models.Index(fields=['innovator', 'visit_date'], name='attendance__innovat_547e9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('innovator', 'visit_date'), name='unique_daily_booking_per_innovator', violation_error_message='You already have a hub booking for this date.'), models.CheckConstraint(condition=models.Q(models.Q(('admitted_at__isnull', True), ('admitted_by__isnull', True), ('status', 'BOOKED')), models.Q(('admitted_at__isnull', False), ('admitted_by__isnull', False), ('status', 'ADMITTED')), _connector='OR'), name='booking_admission_fields_match_status')],
            },
        ),
    ]
